services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5435:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: ${POSTGRES_DB}
    hostname: postgres
    restart: always
    user: postgres
